NOE-33 Final Project-Description-v0.2
lioumis/NOE pull request #16
Opened 2021-04-09 19:23 UTC by NickSxiz

2021-04-10 07:40 UTC, lioumis requested changes
Θα πρέπει να μπουν και screenshots από τις νέες οθόνες στην αναφορά.

2021-04-10 08:30 UTC, ManosBrsls approved these changes

2021-04-10 08:44 UTC, DimitraLirou approved these changes

2021-04-10 08:45 UTC, DimitraLirou approved these changes

2021-04-10 09:05 UTC, ManosBrsls approved these changes

2021-04-10 09:06 UTC, ManosBrsls approved these changes

2021-04-10 18:23 UTC, DimitraLirou approved these changes

2021-04-10 18:25 UTC, DimitraLirou approved these changes

2021-04-11 13:54 UTC, lioumis approved these changes

2021-04-11 13:54 UTC, merged