NOE-60 Final Pdf
lioumis/NOE pull request #35
Opened 2021-04-24 18:50 UTC by NickSxiz

2021-04-25 09:42 UTC, ManosBrsls approved these changes

2021-04-25 13:40 UTC, lioumis requested changes
Μόνο το domain? Θα έπρεπε να υπάρχει όλο το τεχνικό κείμενο + περιγραφές κλάσεων.

2021-04-25 13:48 UTC, NickSxiz commented
Άλλαξε το αρχείο.

2021-04-25 13:50 UTC, lioumis approved these changes

2021-05-10 14:59 UTC, DimitraLirou approved these changes

2021-05-10 14:59 UTC, merged