NOE-56 Final Pdf
lioumis/NOE pull request #36
Opened 2021-04-24 18:51 UTC by NickSxiz

2021-04-25 09:42 UTC, ManosBrsls approved these changes

2021-04-25 13:37 UTC, lioumis requested changes
Σελίδα 3: 
1. "Οθίνη" -> "Οθόνη"
2. "απο" -> "από"
10. "Κύρια οθόνη.." -> "Κύρια οθόνη."

Σελίδα 21:
10. "Ραντεβού , " -> "Ραντεβού, "

Σελίδα 23:
1. "Ιατρού>>στην" -> "Ιατρού>> στην"
7. "αξιολόγηση ." -> "αξιολόγηση."

Σελίδα 24:
3.β.2 **Δεν βγάζει νόημα.** Να προστεθεί κενό εκεί που αρχίζουν τα κόκκινα.

Σελίδα 36:
7.α.1 Κενό μετά τα κόκκινα.

2021-05-05 18:13 UTC, NickSxiz commented
Done!

2021-05-10 14:58 UTC, DimitraLirou approved these changes

2021-05-11 06:05 UTC, lioumis approved these changes

2021-05-11 07:19 UTC, merged