NOE-50 Final Pdf
lioumis/NOE pull request #37
Opened 2021-04-24 18:52 UTC by NickSxiz

2021-04-25 09:42 UTC, ManosBrsls approved these changes

2021-04-25 13:22 UTC, lioumis approved these changes

2021-04-25 13:26 UTC, lioumis commented
Να τονιστούν σωστά οι λέξεις:
1.2 Προϋπολογισμού
1.8 εξιτηρίων

2021-04-25 13:26 UTC, lioumis requested changes
Να τονιστούν σωστά οι λέξεις:
1.2 Προϋπολογισμού
1.8 εξιτηρίων

2021-04-25 13:50 UTC, ManosBrsls approved these changes

2021-05-05 18:05 UTC, NickSxiz commented
Done!

2021-05-10 14:58 UTC, DimitraLirou approved these changes

2021-05-11 06:05 UTC, lioumis approved these changes

2021-05-11 07:19 UTC, merged